import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { sql } from "drizzle-orm";

import { getDb } from "../db/client";
import { vehicles } from "../db/schema";
import { invalidateCatalogCache } from "../services/catalog-service";
import { upsertVehicle } from "../services/catalog-admin-service";
import { saveVehicleImage } from "../services/vehicle-image-service";
import {
  groupImagesByTrim,
  listSourceImages,
  parseImageRecord,
  readSourceImageBuffer,
} from "./vehicle-import";
import { seedByTrimName } from "./vehicle-seed-data";

const DEFAULT_SOURCE =
  "/home/kayd/Downloads/HÌNH ĐĂNG KÝ XE";

function loadEnvFile(filePath: string) {
  return fs.readFile(filePath, "utf8").then((content) => {
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) {
        continue;
      }
      const index = trimmed.indexOf("=");
      if (index === -1) {
        continue;
      }
      const key = trimmed.slice(0, index).trim();
      let value = trimmed.slice(index + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      if (!process.env[key]) {
        process.env[key] = value;
      }
    }
  }).catch(() => undefined);
}

export interface RunImportOptions {
  sourceDir?: string;
  dryRun?: boolean;
}

export interface ImportSummary {
  sourceDir: string;
  imagesProcessed: number;
  vehiclesWritten: number;
  trims: string[];
  dryRun: boolean;
}

export async function ensureVehicleImagesTable() {
  const db = getDb();
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS vehicle_images (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      vehicle_id BIGINT NOT NULL REFERENCES vehicles(id) ON DELETE CASCADE,
      kind VARCHAR(20) NOT NULL,
      color_name VARCHAR(80),
      mime_type VARCHAR(64) NOT NULL DEFAULT 'image/webp',
      data TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CONSTRAINT vehicle_images_kind_chk CHECK (kind IN ('hero', 'color')),
      CONSTRAINT vehicle_images_color_chk CHECK (
        (kind = 'color' AND color_name IS NOT NULL) OR (kind = 'hero' AND color_name IS NULL)
      )
    )
  `);
  await db.execute(sql`
    CREATE UNIQUE INDEX IF NOT EXISTS vehicle_images_vehicle_kind_color_uidx
      ON vehicle_images (vehicle_id, kind, COALESCE(color_name, ''))
  `);
}

export async function runVehicleCatalogImport(
  options: RunImportOptions = {},
): Promise<ImportSummary> {
  const sourceDir = path.resolve(options.sourceDir ?? DEFAULT_SOURCE);
  const dryRun = options.dryRun ?? false;

  const sources = await listSourceImages(sourceDir);
  if (sources.length === 0) {
    throw new Error(`No images found under ${sourceDir}`);
  }

  const parsed = sources.map((sourcePath) => parseImageRecord(sourcePath, sourceDir));
  const grouped = groupImagesByTrim(parsed);

  if (!dryRun) {
    await ensureVehicleImagesTable();

    const db = getDb();
    await db.delete(vehicles);

    for (const row of grouped) {
      const seed = seedByTrimName(row.trimName);
      if (!seed) {
        throw new Error(`Missing seed data for trim ${row.trimName}`);
      }

      const colorPhotos: Record<string, string[]> = {};
      const savedVehicle = await upsertVehicle({
        ...seed,
        availableColors: row.availableColors,
        colorPhotos: {},
        imageUrl: undefined,
        defaultColor: row.defaultColor,
      });

      for (const image of row.images) {
        const buffer = await readSourceImageBuffer(image.sourcePath);
        const savedImage = await saveVehicleImage({
          vehicleId: savedVehicle.id,
          kind: "color",
          colorName: image.colorName,
          buffer,
        });
        if (!colorPhotos[image.colorName]) {
          colorPhotos[image.colorName] = [];
        }
        colorPhotos[image.colorName].push(String(savedImage.id));
      }

      const heroColor = row.defaultColor;
      const heroImageId = colorPhotos[heroColor]?.[0] ?? Object.values(colorPhotos).flat()[0];

      await upsertVehicle({
        ...seed,
        id: savedVehicle.id,
        availableColors: row.availableColors,
        colorPhotos,
        imageUrl: heroImageId,
        defaultColor: row.defaultColor,
      });
    }

    invalidateCatalogCache();
  }

  return {
    sourceDir,
    imagesProcessed: parsed.length,
    vehiclesWritten: grouped.length,
    trims: grouped.map((row) => row.trimName).sort(),
    dryRun,
  };
}

async function main() {
  const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
  await loadEnvFile(path.join(webRoot, ".env.local"));

  const dryRun = process.argv.includes("--dry-run");
  const sourceFlag = process.argv.findIndex((arg) => arg === "--source");
  const sourceDir = sourceFlag >= 0 ? process.argv[sourceFlag + 1] : undefined;

  const summary = await runVehicleCatalogImport({ dryRun, sourceDir });
  console.log(JSON.stringify(summary, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
