import type { AdminVehicle } from "@/types";

/** Vietnamese-market trim data aligned with db/neon-init.sql for folder-backed models. */
export const FOLDER_VEHICLE_SEEDS: AdminVehicle[] = [
  {
    brandCode: "MITSUBISHI",
    categoryCode: "PASSENGER_CAR_7",
    model: "Xpander",
    name: "Xpander Eco",
    seats: 7,
    vehicleType: "ICE",
    year: 2025,
    engineCc: 1499,
    fuelType: "Gasoline",
    transmission: "Automatic",
    listPrice: 598_000_000,
    discountAmount: 102_000_000,
    salePrice: 496_000_000,
    taxBasePrice: 598_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 3_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Nâu",
    deliveryNote: "T2/2025",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; Phim cách nhiệt; Cam hành trình; 10L nhiên liệu",
    quoteSheetName: "Xpander Eco",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "MITSUBISHI",
    categoryCode: "PASSENGER_CAR_7",
    model: "Xpander",
    name: "Xpander Premium",
    seats: 7,
    vehicleType: "ICE",
    year: 2026,
    engineCc: 1499,
    fuelType: "Gasoline",
    transmission: "Automatic",
    listPrice: 659_000_000,
    discountAmount: 105_000_000,
    salePrice: 554_000_000,
    taxBasePrice: 659_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 3_000_000,
    micaPlateFee: 0,
    inspectionFee: 90_000,
    defaultColor: "Trắng",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; Phim cách nhiệt; Cam hành trình; Thảm lót sàn; Hộp đen",
    quoteSheetName: "Xpander Premium",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "MITSUBISHI",
    categoryCode: "PASSENGER_CAR_7",
    model: "Xpander Cross",
    name: "Xpander Cross",
    seats: 7,
    vehicleType: "ICE",
    year: 2025,
    engineCc: 1499,
    fuelType: "Gasoline",
    transmission: "Automatic",
    listPrice: 699_000_000,
    discountAmount: 103_000_000,
    salePrice: 596_000_000,
    taxBasePrice: 699_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 5_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Trắng",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; Phim cách nhiệt; Cam hành trình; 10L nhiên liệu",
    quoteSheetName: "Xpander Cross",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PASSENGER_CAR_4",
    model: "Xforce",
    name: "Xforce GLX",
    seats: 5,
    vehicleType: "ICE",
    year: 2024,
    engineCc: 1499,
    fuelType: "Gasoline",
    transmission: "Automatic",
    listPrice: 605_000_000,
    discountAmount: 70_000_000,
    salePrice: 535_000_000,
    taxBasePrice: 605_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 3_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Bạc",
    deliveryNote: "T10/2024",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; 02 gối đầu; Ví da; Tappi lót sàn",
    quoteSheetName: "Xforce GLX",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PASSENGER_CAR_4",
    model: "Xforce",
    name: "Xforce Premium",
    seats: 5,
    vehicleType: "ICE",
    year: 2025,
    engineCc: 1499,
    fuelType: "Gasoline",
    transmission: "Automatic",
    listPrice: 665_000_000,
    discountAmount: 76_000_000,
    salePrice: 589_000_000,
    taxBasePrice: 665_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 3_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Trắng",
    deliveryNote: "T2/2025",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; Cam hành trình; Phim cách nhiệt",
    quoteSheetName: "Xforce Premium",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PASSENGER_CAR_4",
    model: "Xforce",
    name: "Xforce Ultimate",
    seats: 5,
    vehicleType: "ICE",
    year: 2025,
    engineCc: 1499,
    fuelType: "Gasoline",
    transmission: "Automatic",
    listPrice: 720_000_000,
    discountAmount: 91_000_000,
    salePrice: 629_000_000,
    taxBasePrice: 710_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 5_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Trắng",
    deliveryNote: "T2/2025",
    warrantyNote: "3 năm/100.000km",
    gifts: "Phim cách nhiệt; Cam hành trình; Phủ gầm; 10L nhiên liệu",
    quoteSheetName: "Xforce Ultimate",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PICKUP",
    model: "Triton",
    name: "Triton 4x2 AT GLX",
    seats: 5,
    vehicleType: "ICE",
    year: 2025,
    engineCc: 2442,
    fuelType: "Diesel",
    transmission: "Automatic",
    listPrice: 655_000_000,
    discountAmount: 52_000_000,
    salePrice: 603_000_000,
    taxBasePrice: 655_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 4_000_000,
    micaPlateFee: 0,
    inspectionFee: 70_000,
    defaultColor: "Xám",
    warrantyNote: "5 năm/150.000km",
    gifts: "Bao tay lái; Phim cách nhiệt; Cam hành trình; Áo trùm xe",
    quoteSheetName: "Triton GLX",
    specifications: { Market: "Vietnam", Drive: "4x2", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PICKUP",
    model: "Triton",
    name: "Triton 4x2 Premium",
    seats: 5,
    vehicleType: "ICE",
    year: 2024,
    engineCc: 2442,
    fuelType: "Diesel",
    transmission: "Automatic",
    listPrice: 782_000_000,
    discountAmount: 46_000_000,
    salePrice: 736_000_000,
    taxBasePrice: 782_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 5_000_000,
    micaPlateFee: 400_000,
    inspectionFee: 140_000,
    defaultColor: "Bạc",
    deliveryNote: "T10/2024",
    warrantyNote: "5 năm/150.000km",
    gifts: "Bao tay lái; 02 gối đầu; 10L nhiên liệu",
    quoteSheetName: "Triton Premium",
    specifications: { Market: "Vietnam", Drive: "4x2", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PICKUP",
    model: "Triton",
    name: "Triton 4x4 Athlete",
    seats: 5,
    vehicleType: "ICE",
    year: 2025,
    engineCc: 2442,
    fuelType: "Diesel",
    transmission: "Automatic",
    listPrice: 924_000_000,
    discountAmount: 70_000_000,
    salePrice: 854_000_000,
    taxBasePrice: 924_000_000,
    defaultDeposit: 50_000_000,
    registrationServiceFee: 3_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Trắng",
    warrantyNote: "5 năm/150.000km",
    gifts: "Cam hành trình; Phim cách nhiệt Premium; VETC",
    quoteSheetName: "Triton Athlete",
    specifications: { Market: "Vietnam", Drive: "4x4", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PASSENGER_CAR_4",
    model: "Attrage",
    name: "Attrage MT",
    seats: 5,
    vehicleType: "ICE",
    year: 2024,
    engineCc: 1193,
    fuelType: "Gasoline",
    transmission: "Manual",
    listPrice: 380_000_000,
    discountAmount: 39_000_000,
    salePrice: 341_000_000,
    taxBasePrice: 380_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 5_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Xám",
    deliveryNote: "T2/2025",
    warrantyNote: "3 năm/100.000km",
    gifts: "Phim cách nhiệt; Cam hành trình; Thảm lót sàn",
    quoteSheetName: "Attrage MT",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "mitsubishi",
    categoryCode: "PASSENGER_CAR_4",
    model: "Attrage",
    name: "Attrage CVT Premium",
    seats: 5,
    vehicleType: "ICE",
    year: 2024,
    engineCc: 1193,
    fuelType: "Gasoline",
    transmission: "CVT",
    listPrice: 490_000_000,
    discountAmount: 24_500_000,
    salePrice: 465_500_000,
    taxBasePrice: 490_000_000,
    defaultDeposit: 20_000_000,
    registrationServiceFee: 5_000_000,
    micaPlateFee: 400_000,
    inspectionFee: 140_000,
    defaultColor: "Trắng",
    deliveryNote: "T1/2025",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; 10L nhiên liệu",
    quoteSheetName: "Attrage Premium",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "MITSUBISHI",
    categoryCode: "PASSENGER_CAR_7",
    model: "Destinator",
    name: "Destinator Premium",
    seats: 7,
    vehicleType: "ICE",
    year: 2024,
    engineCc: 1998,
    fuelType: "Gasoline",
    transmission: "CVT",
    listPrice: 780_000_000,
    discountAmount: 85_000_000,
    salePrice: 695_000_000,
    taxBasePrice: 780_000_000,
    defaultDeposit: 50_000_000,
    registrationServiceFee: 3_000_000,
    micaPlateFee: 0,
    inspectionFee: 140_000,
    defaultColor: "Bạc",
    deliveryNote: "T10/2024",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; 02 gối đầu; 10L nhiên liệu",
    quoteSheetName: "Outlander STD",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
  {
    brandCode: "MITSUBISHI",
    categoryCode: "PASSENGER_CAR_7",
    model: "Destinator",
    name: "Destinator Ultimate",
    seats: 7,
    vehicleType: "ICE",
    year: 2024,
    engineCc: 1998,
    fuelType: "Gasoline",
    transmission: "CVT",
    listPrice: 855_000_000,
    discountAmount: 85_000_000,
    salePrice: 770_000_000,
    taxBasePrice: 855_000_000,
    defaultDeposit: 50_000_000,
    registrationServiceFee: 5_000_000,
    micaPlateFee: 400_000,
    inspectionFee: 140_000,
    defaultColor: "Bạc",
    deliveryNote: "T10/2024",
    warrantyNote: "3 năm/100.000km",
    gifts: "Bao tay lái; 10L nhiên liệu",
    quoteSheetName: "Outlander Premium",
    specifications: { Market: "Vietnam", Source: "Bang bao gia" },
    active: true,
  },
];

export const FOLDER_TRIM_BY_MODEL_VERSION: Record<string, Record<string, string>> = {
  XPANDER: {
    ECO: "Xpander Eco",
    PREMIUM: "Xpander Premium",
    CROSS: "Xpander Cross",
  },
  XFORCE: {
    GLX: "Xforce GLX",
    PREMIUM: "Xforce Premium",
    ULTIMATE: "Xforce Ultimate",
  },
  TRITON: {
    GLX: "Triton 4x2 AT GLX",
    PREMIUM: "Triton 4x2 Premium",
    ATHLETE: "Triton 4x4 Athlete",
  },
  ATTRAGE: {
    MT: "Attrage MT",
    PREMIUM: "Attrage CVT Premium",
  },
  DESTINATOR: {
    PREMIUM: "Destinator Premium",
    ULTIMATE: "Destinator Ultimate",
  },
};

export function seedByTrimName(trimName: string): AdminVehicle | undefined {
  return FOLDER_VEHICLE_SEEDS.find((row) => row.name === trimName);
}
