  -- Accessory catalog for quote page (Phụ kiện xe). Run on existing Neon databases.
  -- Images are WebP blobs in accessory_images; accessories.image_url stores the image row id.

  CREATE TABLE IF NOT EXISTS accessories (
      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code        VARCHAR(64)  NOT NULL UNIQUE,
      name        VARCHAR(160) NOT NULL,
      name_en     VARCHAR(160),
      name_zh     VARCHAR(160),
      name_ja     VARCHAR(160),
      amount      NUMERIC(18, 2) NOT NULL,
      image_url   VARCHAR(1000),
      active      BOOLEAN      NOT NULL DEFAULT TRUE,
      sort_order  INTEGER      NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS accessory_images (
      id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      accessory_id BIGINT NOT NULL REFERENCES accessories (id) ON DELETE CASCADE,
      mime_type    VARCHAR(64)  NOT NULL DEFAULT 'image/webp',
      data         TEXT         NOT NULL,
      created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
  );

  CREATE UNIQUE INDEX IF NOT EXISTS accessory_images_accessory_uidx ON accessory_images (accessory_id);

  INSERT INTO accessories (code, name, name_en, name_zh, name_ja, amount, sort_order) VALUES
    ('tint', 'Phim cách nhiệt', 'Heat-insulation film', '隔热膜', '断熱フィルム', 4500000, 1),
    ('dashcam', 'Camera hành trình / hộp đen', 'Dashcam / black box', '行车记录仪 / 黑匣子', 'ドライブレコーダー / ブラックボックス', 2490000, 2),
    ('mats', 'Thảm lót sàn Tappi', 'Tappi floor mats', 'Tappi 脚垫', 'Tappi フロアマット', 1190000, 3),
    ('cover', 'Áo trùm xe', 'Car cover', '车衣', 'ボディカバー', 850000, 4),
    ('undercoat', 'Phủ gầm', 'Underbody coating', '底盘装甲', 'アンダーコート', 2800000, 5),
    ('steering', 'Bao tay lái', 'Steering-wheel cover', '方向盘套', 'ステアリングカバー', 450000, 6),
    ('extinguisher', 'Bình chữa cháy', 'Fire extinguisher', '灭火器', '消火器', 280000, 7),
    ('vetc', 'Dán VETC', 'VETC install', 'VETC 安装', 'VETC 取付', 720000, 8),
    ('camera360', 'Camera 360', '360 camera', '360 影像', '360カメラ', 9500000, 9)
  ON CONFLICT (code) DO NOTHING;
