-- Add location_districts to an existing Neon database (safe to re-run).
-- Regenerate seed: npm run generate:district-seed (from web/).

CREATE TABLE IF NOT EXISTS location_districts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT       NOT NULL REFERENCES locations(id),
    code        VARCHAR(32)  NOT NULL UNIQUE,
    name        VARCHAR(160) NOT NULL,
    name_en     VARCHAR(160) NOT NULL,
    name_zh     VARCHAR(160) NOT NULL,
    name_ja     VARCHAR(160) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_location_districts_location ON location_districts(location_id);

-- Skip insert when already seeded
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM location_districts) = 0 THEN
    RAISE NOTICE 'Run db/location-districts-seed.sql to populate districts (696 rows).';
  END IF;
END $$;
