-- Add customers and link quotes to customer records (safe to re-run).

CREATE TABLE IF NOT EXISTS customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(200) NOT NULL,
    phone         VARCHAR(40),
    street_line   VARCHAR(240),
    location_id   BIGINT REFERENCES locations (id),
    district_id   BIGINT REFERENCES location_districts (id),
    notes         TEXT,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_customers_full_name ON customers (full_name);
CREATE INDEX IF NOT EXISTS idx_customers_active ON customers (is_active) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers (phone);

CREATE TABLE IF NOT EXISTS customer_relationships (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
    related_customer_id  BIGINT NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
    relationship_type    VARCHAR(32) NOT NULL,
    note                 VARCHAR(240),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT customer_relationships_no_self CHECK (customer_id <> related_customer_id),
    CONSTRAINT customer_relationships_unique UNIQUE (customer_id, related_customer_id, relationship_type)
);

CREATE INDEX IF NOT EXISTS idx_customer_relationships_customer ON customer_relationships (customer_id);

ALTER TABLE quote_history
    ADD COLUMN IF NOT EXISTS customer_id BIGINT REFERENCES customers (id);

CREATE INDEX IF NOT EXISTS idx_quote_history_customer ON quote_history (customer_id);
