-- Add bank loan tables to an existing Neon database (safe to re-run).
-- Seed runs only when tables are empty.

CREATE TABLE IF NOT EXISTS banks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(160) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS consulting_employees (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(160) NOT NULL,
    phone       VARCHAR(40),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order  INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bank_loans (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id                  BIGINT NOT NULL REFERENCES banks (id),
    monthly_interest_rate    NUMERIC(8, 4) NOT NULL,
    loan_term_years          INTEGER NOT NULL,
    fixed_rate_period_years  INTEGER NOT NULL DEFAULT 0,
    consulting_employee_id   BIGINT NOT NULL REFERENCES consulting_employees (id),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bank_loans_bank ON bank_loans (bank_id);
CREATE INDEX IF NOT EXISTS idx_bank_loans_employee ON bank_loans (consulting_employee_id);

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM banks) = 0 THEN
    INSERT INTO banks (code, name, sort_order) VALUES
      ('VIETCOMBANK', 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)', 1),
      ('TECHCOMBANK', 'Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)', 2),
      ('VPBANK', 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)', 3),
      ('MB_BANK', 'Ngân hàng TMCP Quân đội (MB Bank)', 4),
      ('BIDV', 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)', 5),
      ('ACB', 'Ngân hàng TMCP Á Châu (ACB)', 6),
      ('SHINHAN', 'Ngân hàng Shinhan Việt Nam', 7);
  END IF;

  IF (SELECT COUNT(*) FROM consulting_employees) = 0 THEN
    INSERT INTO consulting_employees (code, name, phone, sort_order, is_default) VALUES
      ('TVBH_01', 'Nguyễn Văn An', '0901234567', 1, TRUE),
      ('TVBH_02', 'Trần Thị Bình', '0912345678', 2, FALSE),
      ('TVBH_03', 'Lê Minh Cường', '0923456789', 3, FALSE),
      ('TVBH_04', 'Phạm Thu Dung', '0934567890', 4, FALSE);
  END IF;
END $$;
