-- OnRoad / Mitsubishi Vietnam — paste this entire file into Neon SQL Editor and run.
-- Safe to re-run: drops existing demo tables first.

DROP TABLE IF EXISTS fee_rules CASCADE;
DROP TABLE IF EXISTS vehicle_images CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS fee_definitions CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS vehicle_categories CASCADE;
DROP TABLE IF EXISTS dealers CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS app_settings CASCADE;

CREATE TABLE brands (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(40)  NOT NULL UNIQUE,
    name            VARCHAR(80)  NOT NULL,
    tagline         VARCHAR(240),
    market          VARCHAR(80)  NOT NULL,
    accent_color    VARCHAR(16),
    image_url       VARCHAR(1000),
    ready           BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order      INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE vehicle_categories (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                              VARCHAR(64)  NOT NULL UNIQUE,
    name                              VARCHAR(120) NOT NULL,
    description                       VARCHAR(500),
    typical_seats                     INTEGER,
    requires_inspection               BOOLEAN NOT NULL DEFAULT FALSE,
    requires_road_use_fee             BOOLEAN NOT NULL DEFAULT FALSE,
    requires_compulsory_insurance     BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order                        INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE locations (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                      VARCHAR(32)  NOT NULL UNIQUE,
    name                      VARCHAR(160) NOT NULL,
    name_en                   VARCHAR(160) NOT NULL,
    name_zh                   VARCHAR(160) NOT NULL,
    name_ja                   VARCHAR(160) NOT NULL,
    region                    VARCHAR(32)  NOT NULL,
    fee_zone                  VARCHAR(32)  NOT NULL,
    centrally_governed_city   BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE dealers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id    BIGINT NOT NULL REFERENCES brands (id),
    name        VARCHAR(200) NOT NULL,
    address     VARCHAR(400),
    market      VARCHAR(80) NOT NULL DEFAULT 'Vietnam',
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE fee_definitions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(64)  NOT NULL UNIQUE,
    name          VARCHAR(160) NOT NULL,
    description   VARCHAR(500),
    mandatory     BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE vehicles (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id                    BIGINT NOT NULL REFERENCES brands (id),
    category_id                 BIGINT NOT NULL REFERENCES vehicle_categories (id),
    model                       VARCHAR(80)  NOT NULL,
    name                        VARCHAR(180) NOT NULL,
    seats                       INTEGER,
    vehicle_type                VARCHAR(40),
    model_year                  INTEGER,
    engine_cc                   INTEGER,
    fuel_type                   VARCHAR(40),
    transmission                VARCHAR(40),
    list_price                  NUMERIC(18,2) NOT NULL,
    discount_amount             NUMERIC(18,2),
    sale_price                  NUMERIC(18,2),
    tax_base_price              NUMERIC(18,2),
    default_deposit             NUMERIC(18,2),
    registration_service_fee    NUMERIC(18,2),
    mica_plate_fee              NUMERIC(18,2),
    inspection_fee              NUMERIC(18,2),
    default_color               VARCHAR(80),
    available_colors            VARCHAR(240),
    color_photos                TEXT,
    delivery_note               VARCHAR(120),
    warranty_note               VARCHAR(400),
    gifts                       TEXT,
    quote_sheet_name            VARCHAR(80),
    image_url                   VARCHAR(1000),
    specifications              TEXT,
    active                      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE vehicle_images (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id      BIGINT NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    kind            VARCHAR(20) NOT NULL,
    color_name      VARCHAR(80),
    mime_type       VARCHAR(64) NOT NULL DEFAULT 'image/webp',
    data            TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT vehicle_images_kind_chk CHECK (kind IN ('hero', 'color')),
    CONSTRAINT vehicle_images_color_chk CHECK (
        (kind = 'color' AND color_name IS NOT NULL) OR (kind = 'hero' AND color_name IS NULL)
    )
);

CREATE UNIQUE INDEX vehicle_images_vehicle_kind_color_uidx
    ON vehicle_images (vehicle_id, kind, COALESCE(color_name, ''));

CREATE TABLE fee_rules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_definition_id   BIGINT NOT NULL REFERENCES fee_definitions (id),
    category_id         BIGINT REFERENCES vehicle_categories (id),
    location_id         BIGINT REFERENCES locations (id),
    fee_zone            VARCHAR(32),
    calculation_type    VARCHAR(40) NOT NULL,
    fixed_amount        NUMERIC(18,2),
    percentage          NUMERIC(8,4),
    min_amount          NUMERIC(18,2),
    max_amount          NUMERIC(18,2),
    min_engine_cc       INTEGER,
    max_engine_cc       INTEGER,
    min_price           NUMERIC(18,2),
    max_price           NUMERIC(18,2),
    priority            INTEGER NOT NULL DEFAULT 0,
    effective_from      DATE,
    effective_to        DATE,
    active              BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_vehicles_brand ON vehicles (brand_id);
CREATE INDEX idx_vehicles_category ON vehicles (category_id);
CREATE INDEX idx_vehicles_active_brand ON vehicles (brand_id) WHERE active = TRUE;
CREATE INDEX idx_fee_rules_definition ON fee_rules (fee_definition_id);

CREATE TABLE app_settings (
    setting_key VARCHAR(80) PRIMARY KEY,
    payload     TEXT NOT NULL
);

INSERT INTO brands (id, code, name, tagline, market, accent_color, image_url, ready, sort_order) VALUES
(1, 'MITSUBISHI', 'Mitsubishi', 'Bảng báo giá Việt Nam — Moveo New City', 'Vietnam', '#E60012',
 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=80', TRUE, 10),
(2, 'VINFAST', 'VinFast', 'Danh mục Việt Nam sắp có.', 'Vietnam', '#146C43',
 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1400&q=80', FALSE, 20),
(3, 'HONDA', 'Honda', 'Danh mục Việt Nam sắp có.', 'Vietnam', '#E40521',
 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=80', FALSE, 30),
(4, 'TOYOTA', 'Toyota', 'Danh mục Việt Nam sắp có.', 'Vietnam', '#EB0A1E',
 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1400&q=80', FALSE, 40);

INSERT INTO dealers (brand_id, name, address, market) VALUES
(1, 'MITSUBISHI MOVEO NEW CITY - THÀNH PHỐ MỚI BÌNH DƯƠNG',
 '1C, Đường Hùng Vương, Thành phố mới Bình Dương', 'Vietnam');

INSERT INTO vehicle_categories (id, code, name, description, typical_seats, requires_inspection, requires_road_use_fee, requires_compulsory_insurance, sort_order) VALUES
(1, 'MOTORCYCLE', 'Motorcycle', 'Motorbikes and scooters', 2, FALSE, FALSE, TRUE, 10),
(2, 'BICYCLE', 'Bicycle', 'Pedal and e-bikes', 1, FALSE, FALSE, FALSE, 20),
(3, 'PASSENGER_CAR_4', 'Passenger car – 4 seats', 'Sedans and compact SUVs', 5, TRUE, TRUE, TRUE, 30),
(4, 'PASSENGER_CAR_7', 'Passenger car – 7 seats', 'MPVs and family SUVs', 7, TRUE, TRUE, TRUE, 40),
(5, 'PICKUP', 'Pickup truck', 'Light pickup trucks', 5, TRUE, TRUE, TRUE, 50),
(6, 'TRUCK', 'Truck', 'Commercial trucks', 3, TRUE, TRUE, TRUE, 60),
(7, 'VAN', 'Van', 'Passenger and commercial vans', 12, TRUE, TRUE, TRUE, 70),
(8, 'OTHER', 'Other', 'Specialty vehicles', NULL, FALSE, FALSE, TRUE, 80);

INSERT INTO locations (id, code, name, name_en, name_zh, name_ja, region, fee_zone, centrally_governed_city) VALUES
(1,  'HN',  'Hà Nội', 'Hanoi', '河内', 'ハノイ', 'NORTH', 'SPECIAL', TRUE),
(2,  'HP',  'Hải Phòng', 'Hai Phong', '海防', 'ハイフォン', 'NORTH', 'MAJOR', TRUE),
(3,  'BN',  'Bắc Ninh', 'Bac Ninh', '北宁', 'バクニン', 'NORTH', 'STANDARD', FALSE),
(4,  'CB',  'Cao Bằng', 'Cao Bang', '高平', 'カオバン', 'NORTH', 'STANDARD', FALSE),
(5,  'DB',  'Điện Biên', 'Dien Bien', '奠边', 'ディエンビエン', 'NORTH', 'STANDARD', FALSE),
(6,  'HY',  'Hưng Yên', 'Hung Yen', '兴安', 'フンイエン', 'NORTH', 'STANDARD', FALSE),
(7,  'LC',  'Lai Châu', 'Lai Chau', '莱州', 'ライチャウ', 'NORTH', 'STANDARD', FALSE),
(8,  'LS',  'Lạng Sơn', 'Lang Son', '谅山', 'ランソン', 'NORTH', 'STANDARD', FALSE),
(9,  'LO',  'Lào Cai', 'Lao Cai', '老街', 'ラオカイ', 'NORTH', 'STANDARD', FALSE),
(10, 'NB',  'Ninh Bình', 'Ninh Binh', '宁平', 'ニンビン', 'NORTH', 'STANDARD', FALSE),
(11, 'PT',  'Phú Thọ', 'Phu Tho', '富寿', 'フート', 'NORTH', 'STANDARD', FALSE),
(12, 'QN',  'Quảng Ninh', 'Quang Ninh', '广宁', 'クアンニン', 'NORTH', 'STANDARD', FALSE),
(13, 'SL',  'Sơn La', 'Son La', '山罗', 'ソンラ', 'NORTH', 'STANDARD', FALSE),
(14, 'TN',  'Thái Nguyên', 'Thai Nguyen', '太原', 'タイグエン', 'NORTH', 'STANDARD', FALSE),
(15, 'TQ',  'Tuyên Quang', 'Tuyen Quang', '宣光', 'トゥエンクアン', 'NORTH', 'STANDARD', FALSE),
(16, 'HUE', 'Huế', 'Hue', '顺化', 'フエ', 'CENTRAL', 'MAJOR', TRUE),
(17, 'DN',  'Đà Nẵng', 'Da Nang', '岘港', 'ダナン', 'CENTRAL', 'MAJOR', TRUE),
(18, 'HT',  'Hà Tĩnh', 'Ha Tinh', '河静', 'ハティン', 'CENTRAL', 'STANDARD', FALSE),
(19, 'KH',  'Khánh Hòa', 'Khanh Hoa', '庆和', 'カインホア', 'CENTRAL', 'STANDARD', FALSE),
(20, 'NA',  'Nghệ An', 'Nghe An', '义安', 'ゲアン', 'CENTRAL', 'STANDARD', FALSE),
(21, 'QNG', 'Quảng Ngãi', 'Quang Ngai', '广义', 'クアンガイ', 'CENTRAL', 'STANDARD', FALSE),
(22, 'QT',  'Quảng Trị', 'Quang Tri', '广治', 'クアンチ', 'CENTRAL', 'STANDARD', FALSE),
(23, 'TH',  'Thanh Hóa', 'Thanh Hoa', '清化', 'タインホア', 'CENTRAL', 'STANDARD', FALSE),
(24, 'GL',  'Gia Lai', 'Gia Lai', '嘉莱', 'ザライ', 'CENTRAL', 'STANDARD', FALSE),
(25, 'DLK', 'Đắk Lắk', 'Dak Lak', '得乐', 'ダクラク', 'CENTRAL', 'STANDARD', FALSE),
(26, 'LD',  'Lâm Đồng', 'Lam Dong', '林同', 'ラムドン', 'CENTRAL', 'STANDARD', FALSE),
(27, 'HCM', 'Thành phố Hồ Chí Minh', 'Ho Chi Minh City', '胡志明市', 'ホーチミン市', 'SOUTH', 'SPECIAL', TRUE),
(28, 'CT',  'Cần Thơ', 'Can Tho', '芹苴', 'カントー', 'SOUTH', 'MAJOR', TRUE),
(29, 'AG',  'An Giang', 'An Giang', '安江', 'アンザン', 'SOUTH', 'STANDARD', FALSE),
(30, 'CM',  'Cà Mau', 'Ca Mau', '金瓯', 'カマウ', 'SOUTH', 'STANDARD', FALSE),
(31, 'DNI', 'Đồng Nai', 'Dong Nai', '同奈', 'ドンナイ', 'SOUTH', 'STANDARD', FALSE),
(32, 'DT',  'Đồng Tháp', 'Dong Thap', '同塔', 'ドンタップ', 'SOUTH', 'STANDARD', FALSE),
(33, 'TNI', 'Tây Ninh', 'Tay Ninh', '西宁', 'タイニン', 'SOUTH', 'STANDARD', FALSE),
(34, 'VL',  'Vĩnh Long', 'Vinh Long', '永隆', 'ヴィンロン', 'SOUTH', 'STANDARD', FALSE);

INSERT INTO fee_definitions (id, code, name, description, mandatory, sort_order, active) VALUES
(1, 'LICENSE_PLATE', 'Phí bấm biển số', 'Phí bấm biển theo khu vực (huyện / TP / Hà Nội-HCM).', TRUE, 10, TRUE),
(2, 'REGISTRATION_SERVICE', 'Phí dịch vụ đăng ký xe', 'Phí dịch vụ đăng ký xe của đại lý.', TRUE, 20, TRUE),
(3, 'REGISTRATION_TAX', 'Thuế trước bạ (tạm tính)', 'Thuế trước bạ theo giá niêm yết / giá áp thuế.', TRUE, 30, TRUE),
(4, 'ROAD_USE', 'Phí sử dụng đường bộ (1 năm)', 'Phí sử dụng đường bộ 1 năm.', TRUE, 40, TRUE),
(5, 'INSPECTION', 'Lệ phí đăng kiểm', 'Lệ phí đăng kiểm.', TRUE, 50, TRUE),
(6, 'COMPULSORY_INSURANCE', 'Bảo hiểm TNDS + Người ngồi xe (1 năm)', 'Bảo hiểm TNDS bắt buộc + người ngồi trên xe.', TRUE, 60, TRUE),
(7, 'MICA_PLATE', 'Biển số mica', 'Biển số mica (nếu phát sinh).', TRUE, 70, TRUE),
(8, 'OPTIONAL_BODY_INSURANCE', 'Bảo hiểm vật chất thân vỏ xe', 'Bảo hiểm thân vỏ — tùy chọn / tặng theo chương trình.', FALSE, 80, TRUE);

-- Fee rules from sheet "Dữ liệu nguồn". Plate fee and registration tax live in app_settings / YAML, not here.
INSERT INTO fee_rules (fee_definition_id, category_id, fee_zone, calculation_type, fixed_amount, percentage, priority, effective_from, active) VALUES
(2, 3, NULL, 'FIXED', 3000000, NULL, 0, DATE '2026-01-01', TRUE),
(2, 4, NULL, 'FIXED', 3000000, NULL, 0, DATE '2026-01-01', TRUE),
(2, 5, NULL, 'FIXED', 4000000, NULL, 0, DATE '2026-01-01', TRUE),
(4, 3, NULL, 'FIXED', 1560000, NULL, 0, DATE '2026-01-01', TRUE),
(4, 4, NULL, 'FIXED', 1560000, NULL, 0, DATE '2026-01-01', TRUE),
(4, 5, NULL, 'FIXED', 2160000, NULL, 0, DATE '2026-01-01', TRUE),
(5, 3, NULL, 'FIXED', 140000, NULL, 0, DATE '2026-01-01', TRUE),
(5, 4, NULL, 'FIXED', 140000, NULL, 0, DATE '2026-01-01', TRUE),
(5, 5, NULL, 'FIXED', 140000, NULL, 0, DATE '2026-01-01', TRUE),
(6, 3, NULL, 'FIXED', 530700, NULL, 0, DATE '2026-01-01', TRUE),
(6, 4, NULL, 'FIXED', 943400, NULL, 0, DATE '2026-01-01', TRUE),
(6, 5, NULL, 'FIXED', 530700, NULL, 0, DATE '2026-01-01', TRUE),
(7, 3, NULL, 'FIXED', 0, NULL, 0, DATE '2026-01-01', TRUE),
(7, 4, NULL, 'FIXED', 0, NULL, 0, DATE '2026-01-01', TRUE),
(7, 5, NULL, 'FIXED', 0, NULL, 0, DATE '2026-01-01', TRUE),
(8, 3, NULL, 'PERCENT_OF_LIST_PRICE', NULL, 1.50, 0, DATE '2026-01-01', TRUE),
(8, 4, NULL, 'PERCENT_OF_LIST_PRICE', NULL, 1.50, 0, DATE '2026-01-01', TRUE),
(8, 5, NULL, 'PERCENT_OF_LIST_PRICE', NULL, 1.80, 0, DATE '2026-01-01', TRUE);

-- Mitsubishi Vietnam lineup from Bảng báo giá.xlsx
INSERT INTO vehicles (
    brand_id, category_id, model, name, seats, vehicle_type, model_year, engine_cc, fuel_type, transmission,
    list_price, discount_amount, sale_price, tax_base_price, default_deposit,
    registration_service_fee, mica_plate_fee, inspection_fee, default_color, available_colors,
    delivery_note, warranty_note, gifts, quote_sheet_name, image_url, specifications, active
) VALUES
(1, 4, 'Xpander', 'Xpander MT', 7, 'ICE', 2025, 1499, 'Gasoline', 'Manual',
 568000000, 70000000, 498000000, 568000000, 20000000, 3000000, 0, 140000, 'Trắng', 'Trắng,Đen,Bạc,Xám,Nâu',
 'T2/2025', '3 năm/100.000km', 'Bao tay lái; 02 gối đầu; Ví da; Tappi lót sàn; 10L nhiên liệu', 'Xpander MT',
 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Xpander', 'Xpander Eco', 7, 'ICE', 2025, 1499, 'Gasoline', 'Automatic',
 598000000, 102000000, 496000000, 598000000, 20000000, 3000000, 0, 140000, 'Nâu', 'Trắng,Đen,Bạc,Xám,Nâu',
 'T2/2025', '3 năm/100.000km', 'Bao tay lái; Phim cách nhiệt; Cam hành trình; 10L nhiên liệu', 'Xpander Eco',
 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Xpander', 'Xpander Premium', 7, 'ICE', 2026, 1499, 'Gasoline', 'Automatic',
 659000000, 105000000, 554000000, 659000000, 20000000, 3000000, 0, 90000, 'Trắng', 'Trắng,Đen,Bạc,Xám,Nâu',
 NULL, '3 năm/100.000km', 'Bao tay lái; Phim cách nhiệt; Cam hành trình; Thảm lót sàn; Hộp đen', 'Xpander Premium',
 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Xpander Cross', 'Xpander Cross', 7, 'ICE', 2025, 1499, 'Gasoline', 'Automatic',
 699000000, 103000000, 596000000, 699000000, 20000000, 5000000, 0, 140000, 'Trắng', 'Trắng,Đen,Bạc,Xám',
 NULL, '3 năm/100.000km', 'Bao tay lái; Phim cách nhiệt; Cam hành trình; 10L nhiên liệu', 'Xpander Cross',
 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Xforce', 'Xforce GLX', 5, 'ICE', 2024, 1499, 'Gasoline', 'Automatic',
 605000000, 70000000, 535000000, 605000000, 20000000, 3000000, 0, 140000, 'Bạc', 'Trắng,Bạc,Đen,Xám',
 'T10/2024', '3 năm/100.000km', 'Bao tay lái; 02 gối đầu; Ví da; Tappi lót sàn', 'Xforce GLX',
 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Xforce', 'Xforce Exceed', 5, 'ICE', 2024, 1499, 'Gasoline', 'Automatic',
 855000000, 47000000, 808000000, 855000000, 30000000, NULL, 3000000, 140000, 'Trắng', 'Trắng,Bạc,Đen',
 'T12/2024', '3 năm/100.000km', 'Bao tay lái; Phim cách nhiệt; Cam hành trình', 'Xforce Exceed',
 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Xforce', 'Xforce Premium', 5, 'ICE', 2025, 1499, 'Gasoline', 'Automatic',
 665000000, 76000000, 589000000, 665000000, 20000000, 3000000, 0, 140000, 'Trắng', 'Trắng,Bạc,Đen,Nâu',
 'T2/2025', '3 năm/100.000km', 'Bao tay lái; Cam hành trình; Phim cách nhiệt', 'Xforce Premium',
 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Xforce', 'Xforce Ultimate', 5, 'ICE', 2025, 1499, 'Gasoline', 'Automatic',
 720000000, 91000000, 629000000, 710000000, 20000000, 5000000, 0, 140000, 'Trắng', 'Trắng,Bạc,Đen,Nâu',
 'T2/2025', '3 năm/100.000km', 'Phim cách nhiệt; Cam hành trình; Phủ gầm; 10L nhiên liệu', 'Xforce Ultimate',
 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 5, 'Triton', 'Triton 4x2 AT GLX', 5, 'ICE', 2025, 2442, 'Diesel', 'Automatic',
 655000000, 52000000, 603000000, 655000000, 20000000, 4000000, 0, 70000, 'Xám', 'Xám,Bạc,Trắng,Đen',
 NULL, '5 năm/150.000km', 'Bao tay lái; Phim cách nhiệt; Cam hành trình; Áo trùm xe', 'Triton GLX',
 'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Drive":"4x2","Source":"Bang bao gia"}', TRUE),
(1, 5, 'Triton', 'Triton 4x2 Premium', 5, 'ICE', 2024, 2442, 'Diesel', 'Automatic',
 782000000, 46000000, 736000000, 782000000, 20000000, 5000000, 400000, 140000, 'Bạc', 'Bạc,Trắng,Đen',
 'T10/2024', '5 năm/150.000km', 'Bao tay lái; 02 gối đầu; 10L nhiên liệu', 'Triton Premium',
 'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Drive":"4x2","Source":"Bang bao gia"}', TRUE),
(1, 5, 'Triton', 'Triton 4x4 Athlete', 5, 'ICE', 2025, 2442, 'Diesel', 'Automatic',
 924000000, 70000000, 854000000, 924000000, 50000000, 3000000, 0, 140000, 'Trắng', 'Trắng,Bạc,Đen',
 NULL, '5 năm/150.000km', 'Cam hành trình; Phim cách nhiệt Premium; VETC', 'Triton Athlete',
 'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Drive":"4x4","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Attrage', 'Attrage MT', 5, 'ICE', 2024, 1193, 'Gasoline', 'Manual',
 380000000, 39000000, 341000000, 380000000, 20000000, 5000000, 0, 140000, 'Xám', 'Xám,Trắng,Đỏ,Đen',
 'T2/2025', '3 năm/100.000km', 'Phim cách nhiệt; Cam hành trình; Thảm lót sàn', 'Attrage MT',
 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Attrage', 'Attrage CVT', 5, 'ICE', 2024, 1193, 'Gasoline', 'CVT',
 465000000, 40000000, 425000000, 465000000, 20000000, 5000000, 400000, 140000, 'Đỏ', 'Đỏ,Trắng,Xám,Đen',
 'T2/2025', '3 năm/100.000km', 'Phim cách nhiệt; Cam hành trình; 10L nhiên liệu', 'Attrage CVT',
 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 3, 'Attrage', 'Attrage CVT Premium', 5, 'ICE', 2024, 1193, 'Gasoline', 'CVT',
 490000000, 24500000, 465500000, 490000000, 20000000, 5000000, 400000, 140000, 'Trắng', 'Trắng,Đỏ,Xám,Đen',
 'T1/2025', '3 năm/100.000km', 'Bao tay lái; 10L nhiên liệu', 'Attrage Premium',
 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Pajero Sport', 'Pajero 2.4 AT (4x2)', 7, 'ICE', 2024, 2442, 'Diesel', 'Automatic',
 1130000000, 0, 1130000000, 1130000000, 0, 4100000, 400000, 140000, 'Bạc', 'Bạc,Trắng,Đen',
 'T10/2024', '3 năm/100.000km', 'Bao tay lái; 02 gối đầu; 10L nhiên liệu', 'Pajero (4x2)',
 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Drive":"4x2","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Pajero Sport', 'Pajero 2.4 AT (4x4)', 7, 'ICE', 2024, 2442, 'Diesel', 'Automatic',
 1365000000, 0, 1365000000, 1365000000, 0, 4100000, 400000, 140000, 'Bạc', 'Bạc,Trắng,Đen',
 'T10/2024', '3 năm/100.000km', 'Bao tay lái; 02 gối đầu; 10L nhiên liệu', 'Pajero (4x4)',
 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Drive":"4x4","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Destinator', 'Destinator Premium', 7, 'ICE', 2024, 1998, 'Gasoline', 'CVT',
 780000000, 85000000, 695000000, 780000000, 50000000, 3000000, 0, 140000, 'Bạc', 'Bạc,Trắng,Đen',
 'T10/2024', '3 năm/100.000km', 'Bao tay lái; 02 gối đầu; 10L nhiên liệu', 'Outlander STD',
 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE),
(1, 4, 'Destinator', 'Destinator Ultimate', 7, 'ICE', 2024, 1998, 'Gasoline', 'CVT',
 855000000, 85000000, 770000000, 855000000, 50000000, 5000000, 400000, 140000, 'Bạc', 'Bạc,Trắng,Đen',
 'T10/2024', '3 năm/100.000km', 'Bao tay lái; 10L nhiên liệu', 'Outlander Premium',
 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80',
 '{"Market":"Vietnam","Source":"Bang bao gia"}', TRUE);

SELECT setval('brands_id_seq', (SELECT MAX(id) FROM brands));
SELECT setval('vehicle_categories_id_seq', (SELECT MAX(id) FROM vehicle_categories));
SELECT setval('locations_id_seq', (SELECT MAX(id) FROM locations));
SELECT setval('fee_definitions_id_seq', (SELECT MAX(id) FROM fee_definitions));
SELECT setval('vehicles_id_seq', (SELECT MAX(id) FROM vehicles));
SELECT setval('fee_rules_id_seq', (SELECT MAX(id) FROM fee_rules));
SELECT setval('dealers_id_seq', (SELECT MAX(id) FROM dealers));

CREATE TABLE IF NOT EXISTS quote_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(200) NOT NULL,
    customer_address VARCHAR(400),
    vehicle_id BIGINT,
    brand_code VARCHAR(40),
    vehicle_name VARCHAR(180),
    location_id BIGINT,
    location_name VARCHAR(160),
    category_id BIGINT,
    color VARCHAR(80),
    usage_type VARCHAR(20),
    language VARCHAR(8),
    include_optional BOOLEAN NOT NULL DEFAULT FALSE,
    list_price NUMERIC(18,2),
    sale_price NUMERIC(18,2),
    discount_amount NUMERIC(18,2),
    deposit NUMERIC(18,2),
    on_road_total NUMERIC(18,2),
    payload TEXT,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS quote_history_name_idx ON quote_history (customer_name);
